// <auto-generated />
using System;
using System.Collections.Generic;
using DeliveryApp.Infrastructure.Adapters.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryApp.Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260927213358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryApp.Core.Domain.Models.Courier.CourierAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DeliveryApp.Core.Domain.Models.Courier.CourierAggregate.Location#LocationVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("X")
                                .HasColumnType("smallint")
                                .HasColumnName("x");

                            b1.Property<byte>("Y")
                                .HasColumnType("smallint")
                                .HasColumnName("y");
                        });

                    b.HasKey("Id");

                    b.ToTable("courier", (string)null);
                });

            modelBuilder.Entity("DeliveryApp.Core.Domain.Models.Courier.CourierAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourierId")
                        .HasColumnType("uuid")
                        .HasColumnName("courier_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DeliveryApp.Core.Domain.Models.Courier.CourierAssignmentEntity.Location#LocationVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("X")
                                .HasColumnType("smallint")
                                .HasColumnName("location_x");

                            b1.Property<byte>("Y")
                                .HasColumnType("smallint")
                                .HasColumnName("location_y");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.ToTable("courier_assignment", (string)null);
                });

            modelBuilder.Entity("DeliveryApp.Core.Domain.Models.Order.OrderAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CourierId")
                        .HasColumnType("uuid")
                        .HasColumnName("courier_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DeliveryApp.Core.Domain.Models.Order.OrderAggregate.Location#LocationVo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("X")
                                .HasColumnType("smallint")
                                .HasColumnName("location_x");

                            b1.Property<byte>("Y")
                                .HasColumnType("smallint")
                                .HasColumnName("location_y");
                        });

                    b.HasKey("Id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("DeliveryApp.Core.Domain.Models.Courier.CourierAssignmentEntity", b =>
                {
                    b.HasOne("DeliveryApp.Core.Domain.Models.Courier.CourierAggregate", null)
                        .WithMany("Assignments")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryApp.Core.Domain.Models.Courier.CourierAggregate", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
